info:
  component: transfer-api
  project:
    name: transfer-api
    version: 0.0.1-SNAPSHOT

server:
  port: 8077
  contextPath: /transfer-api
  tomcat:
    basedir: /tmp/tomcat

management:
  security:
    enabled: false

spring:
  application:
    name: transfer-api
    h2:
      console:
        path: /h2

  jackson:
    default-property-inclusion: non_null

  jpa:
    show-sql: true
    format-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      dialect: org.hibernate.dialect.H2Dialect
      properties:
        hibernate:
          dialect: org.hibernate.dialect.H2Dialect
          show_sql: true
          hbm2ddl:
            auto: none
          connection:
            release_mode: auto
            autocommit: false
          generate_statistics: true
          cache:
            region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory
            use_second_level_cache: true
            use_query_cache: true
          temp:
            use_jdbc_metadata_defaults: false
        show-sql: false
    properties.hibernate.temp.use_jdbc_metadata_defaults: false

  logging:
  level:
    org:
      hibernate:
        type: trace

  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:transfer
    username: sa
    password: sa

    tomcat:
      max-wait: 60000
      initial-size: 10
      max-active: 150
      test-on-borrow: true