spring.application.name=transfer-api
spring.mvc.pathmatch.matching-strategy=ANT_PATH_MATCHER

# H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2
spring.jpa.hibernate.ddl-auto=create

driverClassName=org.h2.Driver
url=jdbc:h2:mem:csv
username=sa
password=sa

hibernate.dialect=org.hibernate.dialect.H2Dialect

server.port=8080
server.address=0.0.0.0

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
