name: Security Deep Scan (OWASP)

on:
  schedule:
    - cron: "0 2 * * *" # todo dia 02:00 AM
  workflow_dispatch:

jobs:
  dependency-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # 🔥 CACHE (reduz MUITO tempo)
      - name: Cache OWASP DB
        uses: actions/cache@v4
        with:
          path: ~/.dependency-check-data
          key: dependency-check-${{ runner.os }}

      - name: Run OWASP Dependency Check
        run: |
          mvn org.owasp:dependency-check-maven:check \
            -Dnvd.api.key=${{ secrets.NVD_API_KEY }} \
            -Dformat=HTML \
            -DfailBuildOnCVSS=7